name: '2. Build and Deploy Business App'
on:
  workflow_dispatch:
  push:
    paths:
      - './appfiles/**'
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            cp -r ./appfiles/* .
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/dssp:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/dssp:${{ github.sha }}

        - name: Set up kubectl
          run: |
            az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name hackathon-aks

        - name: Create Namespace
          run: |
            kubectl create namespace platform1aks1 || echo "Namespace already exists"

        - name: Deploy to AKS
          run: |
            kubectl apply -f deployment.yaml -n platform1aks1
            kubectl set image deployment/dssp dssp=${{ secrets.REGISTRY_LOGIN_SERVER }}/dssp:${{ github.sha }} -n platform1aks1
            kubectl rollout status deployment/dssp -n platform1aks1

        #- name: 'Deploy to Azure Container Instances'
        #  uses: 'azure/aci-deploy@v1'
        #  with:
        #    resource-group: ${{ secrets.RESOURCE_GROUP }}
        #    dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        #    image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
        #    registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        #    registry-username: ${{ secrets.REGISTRY_USERNAME }}
        #    registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        #    name: aci-sampleapp
        #    location: 'west europe'
