name: '3. Deploy Grafana and Prometheus'

on:
    workflow_dispatch:
    push:
      paths:
        - './monitoring-infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group node_app --name platform1aks1

      - name: Deploy Prometheus
        run: |
          cp -r ./monitoring-infra/* .
          kubectl apply -f ./monitoring-infra/prometheus.yaml

      - name: Deploy Grafana
        run: |
          cp -r ./monitoring-infra/* .
          kubectl apply -f ./monitoring-infra/grafana.yaml

      - name: Wait for Services
        run: |
          echo "Waiting for services to be provisioned..."
          sleep 60 # Adjust based on your needs

      - name: Get External IPs
        run: |
          echo "Prometheus External IP:"
          kubectl get svc -n monitoring prometheus
          echo "Grafana External IP:"
          kubectl get svc -n monitoring grafana
